### ISSUE TITLE
Enhance NeodymiumCucumberRunner with @Browser annotation

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#34]
It would be nice to be able to add a @Browser annotation. This way it would reduce the duplication of test data tables in feature files.

**Comment by marcuskaufmann** [comment]
Actually that is a pretty tough task. The desire to have a browser annotation on a test case to inject a browser instance into the test implies that also multiple browser could be annotated. That in turn means that method multiplication, caused by multiple browser annotations, must be performed on each and every scenario of all affected features files.
So we need to be able to parse feature files, which Cucumber could probably do for us. But we also need to alter the parsed runner hierarchy since we want to execute some parts more often and with different parameters. This also affects test results. At the moment we have a good control about test names which allows us to distinguish different scopes (browser, test data and so on). This will be unlike harder for Cucumber test since we are not able to intercept the naming routines to change it the appropriate way. Thus we are not able at the moment to provide a clean solution to bring annotation based multi-browser support into Cucumber test cases.

**Comment by occupant23** [comment]
We will add a comfort method in the Driver.java that parses the tags of an Scenario and starts the first matching WebDriver using the browser tag from browser.properties.

**Comment by occupant23** [comment]
added the method and added testcases for cucumber execution

**Comment by marcuskaufmann** [comment]
Let's see if we can find a more memorizable term for "SetUpWithBrowserTag"
