### ISSUE TITLE
BrowserOptions/Flags/Capabilities

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#36]
Add a possibility to pass arbitrary flags to the browser (WebDriver).

e.g.  '--disable-gpu' for Chrome

**Comment by marcuskaufmann** [comment]
done
`browserprofile.<tag>.arguments = --my --switches`

**Comment by occupant23** [comment]
works for one argument but not for more, please adjust and add an example to the documentation

**Comment by marcuskaufmann** [comment]
I have changed it to the following:
 - Mutliple arguments need to be separated by an semicolon
 - Arguments mustn't have leading '-' (e.g. chrome: "--headless" needs to be just "headless")
 - Leading/trailing whitespace characters will be trimmed for every argument after splitting on ";" (this is apparently necessary since at least chrome can not handle it)

For instance: `browserprofile.<tag>.arguments = window-position=0,0 ; window-size=400,300 ; headless`

**Comment by marcuskaufmann** [comment]
updated documentation

**Comment by occupant23** [comment]
looks good to me
