### ISSUE TITLE
Update Selenide to 5.1.0 

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#70]
Selenide 5.1.0 is available and provides the newest Selenium which seems to be needed for the current webdrivers.

**Comment by jowerner** [comment]
According to the code, access to a grid should now fail in these situations:

* the grid is protected by username/password
* the grid can be reached via an HTTP proxy only (with/without authentication)

The reason is that the switch to OkHttp is not completely done yet. The credentails/proxy stuff needs to be configured at the OkHttpClient, but not at the (now unused) Apache HttpClient.

**Comment by occupant23** [comment]
ready to test but documentation for the new test-environment proxy needs to be added

**Comment by occupant23** [comment]
added documentation for proxy setup

**Comment by wurzelkuchen** [comment]
rechecked proxy settings, work like a charm
