### ISSUE TITLE
Offer fixed random support

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/neodymium-library#85]
It is often important to randomize things but still being able to replay the sequence later or fix up the randomness. Add support for that to Neo and ensure that order and behavior of test cases before does not influence the outcome.

**Comment by occupant23** [comment]
implementation and documentation done, can be tested

**Comment by oomelianchuk** [comment]
IMO the changes are good, I have nothing to complain about, except for one typo

**Comment by ckeiner** [comment]
* Our implementation of `nextInt(int n)` returns 0 on `n=0`. The normal logic is to throw an Exception. Since our behaviour differs from the standard implementation, we should put this in the Javadoc of the method.
    * Since only values from 0 upwards are allowed, we could use an unsigned int here.
* `nextInt` handles "0" specifically while `getRandom(final int[])` throws an Exception when there is no data or an empty array. It feels inconsistent to throw an error here but not in the former method. Do note, that this is really not that bad and only feels a little weird.

**Comment by occupant23** [comment]
@ckeiner Cab be rechecked.

> Our implementation of nextInt(int n) returns 0 on n=0. The normal logic is to throw an Exception. Since our behaviour differs from the standard implementation, we should put this in the Javadoc of the method.

done

> nextInt handles "0" specifically while getRandom(final int[]) throws an Exception when there is no data or an empty array. It feels inconsistent to throw an error here but not in the former method. Do note, that this is really not that bad and only feels a little weird.

won't fix.  getRandom([0,0,0]) would work, but getRandom([]) doesn't give any hint which result set is expected

**Comment by ckeiner** [comment]
Alright.
